config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # 仮のルーティング
  root 'articles#index'
  resources :tests
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  mount_uploader :icon, IconsUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:icon])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]


  def index
    @articles = Article.all
  end


  def show
  end

 
  def new
    @article = Article.new
  end


  def edit
  end


  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end


    def article_params
      params.require(:article).permit(:title, :author, :text)
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="top-container">
  <%= render partial: 'shared/main_header' %>
</div>
<!-- Blogのメインコンテンツエリア -->
<main id="main" class="l-container clearfix">
	<div class="l-content">
		<div class="row">
      <div class="row-content picks">
        <div class="row-content__item wrap">
          <div class="thumbnail">
            <%= image_tag "cooking１.jpg" %>
            <%# <%= link_to root_path do %>
          </div>
          <h2 class="title">
            <%= link_to '#' do %>
              【料理初心者向け】
              <br>料理学習の始め方
              <br>【３ヶ月で達成できる】
            <% end %>
          </h2>
          <div class="readmore">
            <%= link_to 'READ MORE'%>
          </div>
        </div>
        <div class="row-content__item wrap center">
          <div class="thumbnail">
            <%= image_tag "program1.jpg" %>
            <%# <%= link_to root_path do %>
          </div>
          <h2 class="title">
            <%= link_to '#' do %>
              プログラミングスクール学習
              <br>→就職までの道のり
              <br>【体験談】【インタビュー】
            <% end %>
          </h2>
          <div class="readmore">
            <%= link_to 'READ MORE'%>
          </div>
        </div>
        <div class="row-content__item wrap center">
          <div class="thumbnail">
            <%= image_tag "douga3.jpg" %>
            <%# <%= link_to root_path do %>
          </div>
          <h2 class="title">
            <%= link_to '#' do %>
              人生初の動画編集での、
              <br>裏側を書く
              <br>【仕事ができる学生の特徴】
            <% end %>
          </h2>
          <div class="readmore">
            <%= link_to 'READ MORE'%>
          </div>
        </div>
      </div>
      <!-- articleタグのマークアップ -->
      <article class="itemscope">
        <section>
          <!-- 本文の表示 -->
          <div class="middle-content articlebody">
            <div class="middle-content__item wrap">
              <p class="meta">
                <time itemprop="datePublished">2020/03/31</time>
                <time itemprop="dateModified">(更新日: 2020/04/06)</time>
              </p>
              <!-- タイトル表示 -->
              <h2 class="title">
                <%= link_to '#' do %>
                  【元コストコ店員さん登場】
                  <br>知らなかった商品＆ワザあり
                  <br>【ポイントいっぱいの大量購入品を紹介】
                <% end %>
              </h2>
              <p class="cat">
                <%= link_to '#' do %>
                  料理
                <% end %>
                <%= link_to '#' do %>
                  食べる
                <% end %>
              </p>
              <!-- サムネイルの表示 -->
              <div class="thumbnail">
                <%= link_to root_path,class:"cookingtag" do %>
                  <%= image_tag "cook2.jpg" %>
                <% end %>
              </div>
              <!-- ディスクリプションの表示 -->
              <p class="description">
                可愛くて機能的なエプロンが欲しい！
                かわいい食器を集めたい
                得意料理は煮物と答えた  い…
                ズボラ飯と丁寧飯を作れるようになりたい。
                健康的な食生活に…。
              </p>
              <div class="readmore">
                <%= link_to 'READ MORE'%>
              </div>
            </div>
            <div class="middle-content_item navigation">
              <div class="pull-left">
                <%= link_to '#' do %>
                <i class="fas fa-chevron-left"></i>
                  前のページ
                <% end %>
              </div>
              <div class="pull-right">
                <%= link_to '#' do %>
                  次のページ
                <i class="fas fa-chevron-right"></i>
                <% end %>
              </div>
            </div>
          </div>
        </section>
      </article>
      <%= render partial: 'shared/sidebar'%>
    </div>
  </div>
</main>

<footer>
</footer>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KAblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_main_header.html.erb
<header class="main-header">
  <h1 id= "header-logo" class= "header-logo">
    <%= link_to root_path do %>
    <span><a href="https://fontmeme.com/ja/font-trolls/"><img src="https://fontmeme.com/permalink/200314/a99fd491f62f75c89ee2d828e5ec7f83.png" alt="font-trolls" border="0"></a></span>
    <% end %>
  </h1>
  <nav id="gnavi-pc" class="gnavi-pc">
    <div class="header__menu-box">
      <ul class="image-gallery">
        <li>
          <%= link_to root_path ,class:"writer" do %>By Kaoru Koyama
          <span>Writer</span>
          <% end %>
        </li>
        <li class="header__menu-box--center__category">
          <%= link_to root_path,class:"header__menu-box--center__icon" do %>ご紹介
          <i class="fas fa-sort-down"></i>
          <span class="caret">Profile</span>
          <% end %>
          <ul class="header__menu-box--center__parents">
            <li>
              <%= link_to root_path do %>プロフィール
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>料理
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>プログラミング
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>ブログ
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>ゲーム
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>フリーランス
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>動画編集
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>転職活動
              <% end %>
            </li>
          </ul>
        </li>
        <li class="bookingnow">
          <%= link_to root_path do %>ポートフォリオ
          <span>Portfolio</span>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
  <div class="header-icon">
    <ul class="clearfix">
      <li class="base">
      </li>
      <li class="cart">
        <%= link_to root_path do %>
        <i class="fas fa-home"></i>
        <%# <i class="fas fa-shopping-cart"></i>%>
        <% end %>
      </li>
    </ul>
  </div>
  <%# 隠しメニューが非表示の時に使うclass %>
  <%# <div id="mobile-menu-toggle" class="mobile-menu-toggle">
    <img src="//youange.com/shop/images/mobile-menu-toggle.png">
  </div> %>
  <%# 隠しメニューが表示された時に使うclass %>
  <div class="mobile-menu-wrap">
    <nav class="gnavi-sp" id="gnavi-sp">
      <ul class="menu">
        <li>
          <%= link_to root_path do %>プロフィール
          <% end %>
          <ul class="sub-menu">
            <li>
              <%= link_to root_path do %>料理
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>動画編集
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>プログラミング
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>転職活動
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>ポートフォリオ
              <% end %>
            </li>
          </ul>
        </li>
    </nav>
  </div>

  <div class="hamburger" id="js-hamburger" onclick="toggleNav()">
    <p>MENU</p>
    <span class="hamburger__line hamburger__line--1"></span>
    <span class="hamburger__line hamburger__line--2"></span>
    <span class="hamburger__line hamburger__line--3"></span>
  </div>
  <div class="black-bg" id="js-black-bg"></div>
</header>

app/views/shared/_sidebar.html.erb
<aside class="sidebar" id="sidebar">
  <div class="middle-content author">
    <% if user_signed_in? %>
      <div class="usericon">
        <% if current_user.icon.nil? %>
          <%= image_tag "mrkr-icon.png" %>
        <% else %>
          <%= image_tag current_user.icon %>
        <% end %>
      </div>
    <% else %>
      <%= image_tag "mrkr-icon.png" %>
    <% end %>
    <h4>
      <span>カオ</span>
    </h4>
    <hr>
    <p>
      料理・プログラミングを愛しております,転職活動内容も発信,経歴：派遣事務→正社員事務9年→派遣経理（今ココ）→TECH56期卒業
      /働きながら転職活動しながら個人アプリ作成中,
      HTML/CSS/Javascript/Rudy/Rails
    </p>
    <div class="side-menu">
      <div class='menu-content'>
        <%= link_to '記事を投稿'%>
        <i class="fas fa-chevron-right"></i>
      </div>
      <div class='menu-search'>
        <%= link_to '記事を検索'%>
        <i class="fas fa-chevron-right"></i>
      </div>
      <div class='menu-content'>
        <% if user_signed_in? %>
          <%= link_to 'マイページ'%>
          <i class="fas fa-chevron-right"></i>
          </div>
        <% else %>
          <%= link_to 'ログイン', user_session_path%>
          <i class="fas fa-chevron-right"></i>
        <% end %>
      </div>
      <div class='menu-content'>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete%>
        <i class="fas fa-chevron-right"></i>
      </div>
    </div>
  </div>
</aside>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <div class='link-login'>
    <%= link_to "ログイン", new_session_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <div class='link-signup'>
    <%= link_to "登録がまだの方はこちら", new_registration_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <div class='link-forget'>
    <%= link_to "パスワードをお忘れですか？", new_password_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>